// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","id":"1"},"2":{"path":"/login","parentId":"1","id":"2"},"3":{"path":"/register","id":"3"},"4":{"path":"/register","parentId":"3","id":"4"},"5":{"path":"/forgot-password","id":"5"},"6":{"path":"/forgot-password","parentId":"5","id":"6"},"7":{"path":"/reset-password","id":"7"},"8":{"path":"/reset-password","parentId":"7","id":"8"},"9":{"path":"/","id":"9"},"10":{"path":"/","id":"10"},"11":{"path":"equipment","parentId":"10","id":"11"},"12":{"path":"equipment/:id","parentId":"10","id":"12"},"13":{"path":"borrow-request/create","parentId":"10","id":"13"},"14":{"path":"borrow-request","parentId":"10","id":"14"},"15":{"path":"notifications","parentId":"10","id":"15"},"16":{"path":"profile","parentId":"10","id":"16"},"17":{"path":"/admin","id":"17"},"18":{"path":"","redirect":"/admin/dashboard","parentId":"17","id":"18"},"19":{"path":"dashboard","parentId":"17","id":"19"},"20":{"path":"requests","parentId":"17","id":"20"},"21":{"path":"requests/:id","parentId":"17","id":"21"},"22":{"path":"equipment","parentId":"17","id":"22"},"23":{"path":"users","parentId":"17","id":"23"},"24":{"path":"reports","parentId":"17","id":"24"},"25":{"path":"notifications","parentId":"17","id":"25"},"26":{"path":"profile","parentId":"17","id":"26"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__AuthLayout" */'@/layouts/AuthLayout.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "layouts__AuthLayout" */'@/layouts/AuthLayout.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__register__index" */'@/pages/register/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "layouts__AuthLayout" */'@/layouts/AuthLayout.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__forgot-password__index" */'@/pages/forgot-password/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "layouts__AuthLayout" */'@/layouts/AuthLayout.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__reset-password__index" */'@/pages/reset-password/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "layouts__StudentLayout" */'@/layouts/StudentLayout.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__equipment__index" */'@/pages/equipment/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__equipment__id" */'@/pages/equipment/[id].tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__borrow-request__create" */'@/pages/borrow-request/create.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__borrow-request__index" */'@/pages/borrow-request/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__notifications__index" */'@/pages/notifications/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__profile__index" */'@/pages/profile/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "layouts__AdminLayout" */'@/layouts/AdminLayout.tsx')),
'18': React.lazy(() => import('./EmptyRoute')),
'19': React.lazy(() => import(/* webpackChunkName: "p__admin__dashboard__index" */'@/pages/admin/dashboard/index.tsx')),
'20': React.lazy(() => import(/* webpackChunkName: "p__admin__requests__index" */'@/pages/admin/requests/index.tsx')),
'21': React.lazy(() => import(/* webpackChunkName: "p__admin__requests__id" */'@/pages/admin/requests/[id].tsx')),
'22': React.lazy(() => import(/* webpackChunkName: "p__admin__equipment__index" */'@/pages/admin/equipment/index.tsx')),
'23': React.lazy(() => import(/* webpackChunkName: "p__admin__users__index" */'@/pages/admin/users/index.tsx')),
'24': React.lazy(() => import(/* webpackChunkName: "p__admin__reports__index" */'@/pages/admin/reports/index.tsx')),
'25': React.lazy(() => import(/* webpackChunkName: "p__admin__notifications__index" */'@/pages/admin/notifications/index.tsx')),
'26': React.lazy(() => import(/* webpackChunkName: "p__admin__profile__index" */'@/pages/admin/profile/index.tsx')),
},
  };
}
