// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/home/minhchien/RIPT1307-02-2026-Nhom-9-KTHP/apps/web/src/.umi/plugin-access';
export { Provider, useModel } from '/home/minhchien/RIPT1307-02-2026-Nhom-9-KTHP/apps/web/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/home/minhchien/RIPT1307-02-2026-Nhom-9-KTHP/apps/web/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/home/minhchien/RIPT1307-02-2026-Nhom-9-KTHP/apps/web/src/.umi/plugin-access/types.d';
export * from '/home/minhchien/RIPT1307-02-2026-Nhom-9-KTHP/apps/web/src/.umi/plugin-antd/types.d';
export * from '/home/minhchien/RIPT1307-02-2026-Nhom-9-KTHP/apps/web/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/home/minhchien/RIPT1307-02-2026-Nhom-9-KTHP/node_modules/.pnpm/@umijs+renderer-react@4.6.55_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/home/minhchien/RIPT1307-02-2026-Nhom-9-KTHP/node_modules/.pnpm/@umijs+renderer-react@4.6.55_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/home/minhchien/RIPT1307-02-2026-Nhom-9-KTHP/node_modules/.pnpm/umi@4.6.55_@babel+core@7.29.0_@types+node@20.19.41_@types+react@18.3.29_eslint@8.35.0_l_14918777f9a5a715e0133360c4ccb948/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
